/*
	MER DE UNA LINEA DE SUPER MERCADOS
*/

CREATE TABLE CARGO
	(COD_CARG NUMBER(2) CONSTRAINT CARGO_COD_CARG_PK PRIMARY KEY,
	CARGO VARCHAR2(15) NOT NULL,
	SALARIO NUMBER(10,2) NOT NULL);

CREATE TABLE PUNTO_VENTA
	(COD_PVENTA NUMBER(2) CONSTRAINT PUNTO_VENTA_COD_PVENTA_PK PRIMARY KEY,
	NOMBRE_PVENTA VARCHAR2(30) NOT NULL,
	DIR_PVENTA VARCHAR2(40) );

CREATE TABLE EMPLEADO
	(ID_EMP NUMBER(4) CONSTRAINT EMPLEADO_ID_EMP_PK PRIMARY KEY,
	APELLIDO_EMP VARCHAR2(15) NOT NULL,
	NOMBRE_EMP VARCHAR2(15) NOT NULL,
	TEL_EMP VARCHAR2(10),
	EMAIL_EMP VARCHAR2(30),
	DIR_EMP VARCHAR2(40),
	COD_CARG NUMBER(2) NOT NULL,
	COD_PVENTA NUMBER(2) NOT NULL,
	CONSTRAINT EMPLEADO_COD_CARG_FK FOREIGN KEY (COD_CARG) REFERENCES CARGO (COD_CARG),	
	CONSTRAINT EMPLEADO_COD_PVENTA_FK FOREIGN KEY (COD_PVENTA) REFERENCES PUNTO_VENTA(COD_PVENTA) );

CREATE TABLE CLIENTE
	(ID_CLIE NUMBER(4) CONSTRAINT CLIENTE_ID_CLIE_PK PRIMARY KEY,
	APELLIDO_CLIE VARCHAR2(15) NOT NULL,
	NOMBRE_CLIE VARCHAR2(15) NOT NULL,
	TEL_CLIE VARCHAR2(10),
	EMAIL_CLIE VARCHAR2(30),
	DIR_CLIE VARCHAR2(40) );

CREATE TABLE CLIE_PUNTO
	(ID_CLIE NUMBER(4) NOT NULL,
	COD_PVENTA NUMBER(2) NOT NULL,
	CONSTRAINT CLIE_PUNTO_ID_CLIE_FK FOREIGN KEY (ID_CLIE) REFERENCES CLIENTE(ID_CLIE),
	CONSTRAINT CLIE_PUNTO_COD_PVENTA_FK FOREIGN KEY (COD_PVENTA) REFERENCES PUNTO_VENTA(COD_PVENTA) );

CREATE TABLE PROVEEDOR
	(ID_PROV NUMBER(4) CONSTRAINT PROVEE_ID_PROV_PK PRIMARY KEY,
	NOM_EMPRESA VARCHAR2(30) NOT NULL,
	DIR_PROV VARCHAR2(40));

CREATE TABLE MED_PAGO
	(COD_MPAGO NUMBER(2) CONSTRAINT COD_MPAGO_PK PRIMARY KEY,
	MPAGO VARCHAR2(20) NOT NULL);

CREATE TABLE ORDEN_COM
	(COD_ORDEN NUMBER(10) CONSTRAINT ORDEN_COM_COD_ORDEN_PK PRIMARY KEY,
	FECHA_ORDEN DATE NOT NULL,
	PREC_TOT_ORDEN NUMBER(10,2),
	COD_MPAGO NUMBER(2) NOT NULL,
	ID_EMP NUMBER(4) NOT NULL,
	ID_PROV NUMBER(4) NOT NULL,
	CONSTRAINT ORDEN_COM_COD_MPAGO_FK FOREIGN KEY (COD_MPAGO) REFERENCES MED_PAGO(COD_MPAGO),
	CONSTRAINT ORDEN_COM_ID_EMP_FK FOREIGN KEY (ID_EMP) REFERENCES EMPLEADO(ID_EMP),
	CONSTRAINT ORDEN_COM_ID_PROV_FK FOREIGN KEY (ID_PROV) REFERENCES PROVEEDOR(ID_PROV) );

CREATE TABLE DETALLE_ORDEN
	(COD_BARRAS NUMBER(10) CONSTRAINT DETALLE_ORDEN_COD_BARRAS_PK PRIMARY KEY,
	UPREC_COM NUMBER(8,2) NOT NULL,
	COD_ORDEN NUMBER(10) NOT NULL,
	CONSTRAINT DETALLE_ORDEN_COD_ORDEN_FK FOREIGN KEY (COD_ORDEN) REFERENCES ORDEN_COM(COD_ORDEN) );

CREATE TABLE CATEGORIA_PROD
	(COD_CATEG NUMBER(4) CONSTRAINT CATEG_COD_CATEG_PK PRIMARY KEY,
	NOM_CATEG VARCHAR2(30) NOT NULL);

CREATE TABLE PRODUCTO
	(COD_PROD NUMBER(6) CONSTRAINT PRODUCTO_COD_PROD_PK PRIMARY KEY,
	NOM_PROD VARCHAR2(30) NOT NULL,
	DESC_PROD VARCHAR2(40),
	COD_CATEG NUMBER(4) NOT NULL,
	CONSTRAINT PRODUCTO_COD_CATEG_FK FOREIGN KEY (COD_CATEG) REFERENCES CATEGORIA_PROD(COD_CATEG) );
    
CREATE TABLE TIPO_ESTADO
	(COD_EST NUMBER(2) CONSTRAINT TIPO_EST_COD_EST_PK PRIMARY KEY,
	DESC_EST VARCHAR2(20) NOT NULL);

CREATE TABLE INVENTARIO
	(COD_BARRAS NUMBER(10) CONSTRAINT INVENT_COD_BARRAS_PK PRIMARY KEY,
	LOTE_PROD VARCHAR2(10) NOT NULL,
	FECHA_CADUC DATE NOT NULL,
	COD_EST NUMBER(2) NOT NULL,
	COD_PROD NUMBER(6) NOT NULL,
	CONSTRAINT INVENT_COD_EST_FK FOREIGN KEY (COD_EST) REFERENCES TIPO_ESTADO(COD_EST),
	CONSTRAINT INVENT_COD_PROD_FK FOREIGN KEY (COD_PROD) REFERENCES PRODUCTO(COD_PROD),
	CONSTRAINT INVENT_COD_BARRAS_FK FOREIGN KEY (COD_BARRAS) REFERENCES DETALLE_ORDEN(COD_BARRAS) );

CREATE TABLE FACTURA_VENTA
	(COD_FAC_VENT NUMBER(10) CONSTRAINT FACT_VENT_COD_FAC_VENT_PK PRIMARY KEY,
	FECHA_VENT DATE NOT NULL,
	ID_EMP NUMBER(4) NOT NULL,
	ID_CLIE NUMBER(4) NOT NULL,
	PREC_TOT_VENT NUMBER(9,2),
	COD_MPAGO NUMBER(2) NOT NULL,
	CONSTRAINT FACT_VENT_ID_EMP_FK FOREIGN KEY (ID_EMP) REFERENCES EMPLEADO(ID_EMP),
	CONSTRAINT FACT_VENT_ID_CLIE_FK FOREIGN KEY (ID_CLIE) REFERENCES CLIENTE(ID_CLIE),
	CONSTRAINT FACT_VENT_COD_MPAGO_FK FOREIGN KEY (COD_MPAGO) REFERENCES MED_PAGO(COD_MPAGO) );	

CREATE TABLE DETALLE_VENT
	(COD_BARRAS NUMBER(10) CONSTRAINT DETALLE_VENT_COD_BARRAS_PK PRIMARY KEY,
	UPREC_VENT NUMBER(8,2) NOT NULL,
	COD_FAC_VENT NUMBER(10) NOT NULL,
	CONSTRAINT DETALLE_VENT_COD_FAC_VENT_FK FOREIGN KEY (COD_FAC_VENT) REFERENCES FACTURA_VENTA(COD_FAC_VENT),
	CONSTRAINT DETALLE_VENT_COD_BARRAS_FK FOREIGN KEY (COD_BARRAS) REFERENCES INVENTARIO(COD_BARRAS) );

/*
EL SCRIPT DROPER ES PARA BORRAR TABLAS
DROPER:
DROP TABLE DETALLE_VENT;
DROP TABLE FACTURA_VENTA;
DROP TABLE INVENTARIO;
DROP TABLE TIPO_ESTADO;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA_PROD;
DROP TABLE DETALLE_ORDEN;
DROP TABLE ORDEN_COM;
DROP TABLE MED_PAGO;
DROP TABLE PROVEEDOR;
DROP TABLE CLIE_PUNTO;
DROP TABLE PUNTO_VENTA;
DROP TABLE CLIENTE;
DROP TABLE EMPLEADO;
DROP TABLE CARGO;
EL SCRIPT PROOF ERA PARA PROBAR LA CREACION DE TABLAS
EL SCRIPT SUPER ES EL DEFINITIVO
*/